### ISSUE TITLE
Preserve sphinx theme set in project configuration

### ISSUE THREAD

**Issue by drdavella** [asdf-format/sphinx-asdf#12]
Currently the generated schema documentation does not conform to the theme that is set in the project's `docs/conf.py`. This is because we use the sphinx bootstrap stylesheets to generate schema documentation, so they get pulled in regardless of whether the project is using `sphinx-bootstrap-theme` or not.

I'm not sure whether this will be possible and/or how much effort it is worth.

**Comment by drdavella** [comment]
This is just a shot in the dark, but it's possible that we could fix this by calling `super()` in this section of the template: https://github.com/spacetelescope/sphinx-asdf/blob/04f56ef65acaf38ff6202ce3de7d25c9af93456a/sphinx_asdf/templates/schema.html#L3-L4

**Comment by braingram** [comment]
I believe this was fixed in: https://github.com/asdf-format/sphinx-asdf/pull/88
