### ISSUE TITLE
Parsing all files add a huge overhead 

### ISSUE THREAD

**Issue by saimn** [asdf-format/sphinx-asdf#14]
To find the asdf directive it seems that this plugin relies on fully parsing all the rst files, which on astropy introduces a huge overhead:
```
find_autoasdf_directives /home/simon/Dev/astro/astropy/docs/api/astropy.wcs.wcsapi.BaseHighLevelWCS.rst : 0.19 sec.
find_autoasdf_directives /home/simon/Dev/astro/astropy/docs/api/astropy.tests.helper.check_pickling_recovery.rst : 0.03 sec.
find_autoasdf_directives /home/simon/Dev/astro/astropy/docs/units/standard_units.rst : 0.08 sec.
find_autoasdf_directives /home/simon/Dev/astro/astropy/docs/api/astropy.utils.misc.JsonCustomEncoder.rst : 0.08 sec.
find_autoasdf_directives /home/simon/Dev/astro/astropy/docs/api/astropy.nddata.PartialOverlapError.rst : 0.03 sec.
find_autoschema_references : 217.85 sec.
```

I don't know much about Sphinx plugins API but I'm surprised that there is no better way to proceed ?

For reference the code involved here:
https://github.com/spacetelescope/sphinx-asdf/blob/64ed11ab19a007bd1861c82cc2710f1e6ec61286/sphinx_asdf/connections.py#L19-L48

**Comment by pllim** [comment]
Since we removed this as astropy dependency (for now) in astropy/astropy#8644 , I am closing this without merge. We can revisit in the future when this package has a proper maintainer. Thanks anyway!

**Comment by pllim** [comment]
(Ops, sorry... commented on wrong one.)

**Comment by drdavella** [comment]
FWIW, this is basically the same way that the sphinx autosummary plugin works, but I'm sorry that it has caused a problem in astropy.

Maybe we should use a configuration variable that tells this plugin on only process files in a particular subdirectory so it doesn't end up parsing every document.

**Comment by braingram** [comment]
Closing this as the plugin is no longer used by astropy and as noted follows the same pattern used by autosummary.
